### ISSUE TITLE
How to get Access Toke and Refresh Token

### ISSUE THREAD

**Issue by bussoladesenvolvimento** [Azure-Samples/ms-identity-android-kotlin#14]
How can we get the Access Token and Refresh Token through the APP to work on our API?

**Comment by Areyana** [comment]
Same problem, any help ?

**Comment by eugenSt20** [comment]
Need help. How we can get refresh token?

**Comment by Shaif821** [comment]
Still no update?

**Comment by negoe** [comment]
Please follow the comprehensive guidance here https://learn.microsoft.com/en-us/entra/msal/android/
