### ISSUE TITLE
Not Able to access outlook accounts like other ms apps like yammer and to do list.

### ISSUE THREAD

**Issue by A86S** [Azure-Samples/ms-identity-android-kotlin#8]
Hi @shoatman can you look into this , i am not able to access outlook accounts in my device on login screen 

https://stackoverflow.com/questions/58202286/login-always-opens-web-dialog-even-though-native-microsoft-apps-are-installed-m

one more thing, is it related to this error ?
This request is not eligible to use the broker. Do not check sharedDevice mode and return false immediately. Android 25

i have checked the yammer app and noticed that they have token manager and token services to get shared accounts list on the device to short logged in but not able to find the same way with this sample. 

Please guide me on this.

**Comment by shoatman** [comment]
You may need to register a new redirect URI compatible with the Microsoft auth brokers.  See the following for more information: [https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth](https://docs.microsoft.com/en-us/azure/active-directory/develop/brokered-auth)
